#huggingface
project_name: "JurAIGesetze"
base_model_id: "DiscoResearch/DiscoLM_German_7b_v1"
push_to_hub: True
repo_id: "kdot/"
hf_token: "your_hf_token"

#data
train_path: "train/dummyData/selfSupervised/train.jsonl"
val_path: "train/dummyData/selfSupervised/eval.jsonl"

#model
learning_rate: "2e-5"
max_steps: 500
batch_size: "2"
block_size: 2048
trainer: "sft"
warmup_ratio: "0.1"
weight_decay: "0.01"
gradient_accumulation_steps: "4"
fp16: True
use_peft: "true"
use_int4: "true"
lora_r: "16"
lora_alpha: "32"
lora_dropout: "0.045"

#wandb
wandb_project: Null # if you want to use wandb, set this to your project name