project_name: JurAIGesetze
model_name: jphme/em_german_leo_mistral
push_to_hub: true
repo_id: LongIsland/JurAIGesetzeTry
learning_rate: 2e-5
num_epochs: 4
batch_size: 2
block_size: 512
trainer: sft
warmup_ratio: 0.1
weight_decay: 0.01
gradient_accumulation: 4
use_fp16: true
use_peft: true
use_int4: true
lora_r: 16
lora_alpha: 32
lora_dropout: 0.045
