# huggingface
base_model_id: DiscoResearch/DiscoLM_German_7b_v1
repo_id: juraiLLM/supervised_conversational
push_to_hub: true
repo_resume_id: juraiLLM/supervised_conversational
repo_id: juraiLLM/supervised_conversational_20_02_2024

# data
train_path: train/dummyData/selfSupervised/train.jsonl
val_path: Null
test_path: "src/ml/test/test_set/test_sample.csv"
test_result_path: "src/ml/test/results/"

# model
training_type: supervised
learning_rate: 2e-5
max_steps: 43912
batch_size: 2
block_size: 4096
overlap: 200
trainer: sft
warmup_ratio: 0.1
weight_decay: 0.01
gradient_accumulation_steps: 4
fp16: true
use_peft: true
use_int4: true
logging_steps: 500
save_steps: 2500
eval_steps: 2500
lora_r: 16
lora_alpha: 32
lora_dropout: 0.045
use_rslora: false 

# wandb
wandb_project: Null # if you want to use wandb, set this to your project name
